/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/get-proposals": {
    /**
     * Get proposals from your agent
     * @description Scope3 calls this endpoint when setting up a campaign to ask for proposals
     * from your agent on how you would approach execution.
     *
     * Analyze the campaign and respond with proposals, budget capacity,
     * and your pricing model.
     */
    post: operations["get_proposed_tactics"];
  };
  "/accept-proposal": {
    /**
     * Accept or decline proposal assignment
     * @description Scope3 calls this when your proposal is accepted and you are assigned to manage a tactic.
     * You should acknowledge and begin setup, or decline if you can't fulfill it.
     *
     * The campaign context contains everything you need: budget, schedule,
     * targeting constraints, creatives, and any custom fields.
     */
    post: operations["accept_proposal"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Budget range for campaign planning (buyer typically won't reveal full budget) */
    BudgetRange: {
      /**
       * @description Minimum budget available
       * @example 50000
       */
      min?: number;
      /**
       * @description Maximum budget available
       * @example 150000
       */
      max?: number;
      /**
       * @description Currency for budget (ISO 4217 code)
       * @default USD
       * @example USD
       */
      currency?: string;
    };
    TacticPricing: {
      /**
       * @description How the outcome agent charges for this tactic (revshare or cost_per_unit)
       * @example revshare
       * @enum {string}
       */
      method: "revshare" | "cost_per_unit";
      /**
       * @description Rate for the pricing method (e.g., 0.15 for 15% revshare, 2.50 for $2.50 CPM)
       * @example 0.15
       */
      rate: number;
      /**
       * @description Pricing unit (required when method is cost_per_unit)
       * @example cpm
       * @enum {string}
       */
      unit?: "cpm" | "cpc" | "cpa" | "cpv" | "cpcv";
      /**
       * @description Currency for pricing (ISO 4217 code)
       * @default USD
       * @example USD
       */
      currency?: string;
    };
    CustomField: {
      /**
       * @description Name of the custom field
       * @example targetVCPM
       */
      fieldName?: string;
      /**
       * @description Data type of the field
       * @example number
       * @enum {string}
       */
      fieldType?: "string" | "number" | "boolean" | "array" | "object";
      /**
       * @description Help text explaining what this field does
       * @example Target vCPM in USD
       */
      description?: string;
    };
    /** @description Product reference from sales agent */
    Product: {
      /**
       * @description URL of the sales agent offering this product
       * @example https://sales-agent.example.com
       */
      sales_agent_url: string;
      /**
       * @description Product reference ID from the sales agent
       * @example prod_premium_display
       */
      product_ref: string;
      /**
       * @description Pricing option ID for this product
       * @example pricing_opt_123
       */
      pricing_option_id: string;
    };
    GetProposalsRequest: {
      /**
       * @description Campaign ID
       * @example camp_123
       */
      campaignId: string;
      budgetRange?: components["schemas"]["BudgetRange"];
      /**
       * Format: date-time
       * @description Campaign start date in UTC (ISO 8601 format)
       * @example 2025-01-01T00:00:00Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @description Campaign end date in UTC (ISO 8601 format)
       * @example 2025-01-31T23:59:59Z
       */
      endDate?: string;
      /**
       * @description Advertising channels (from ADCP specification)
       * @example [
       *   "display",
       *   "video"
       * ]
       */
      channels?: ("display" | "video" | "native" | "audio" | "connected_tv")[];
      /**
       * @description ISO 3166-1 alpha-2 country codes
       * @example [
       *   "US",
       *   "CA"
       * ]
       */
      countries?: string[];
      /**
       * @description Campaign brief text
       * @example Launch campaign for new product...
       */
      brief?: string;
      /** @description Optional product objects to include in proposals (full product details, not just IDs) */
      products?: components["schemas"]["Product"][];
      /**
       * @description Optional property list IDs for targeting (references Scope3 property lists)
       * @example [
       *   123,
       *   456
       * ]
       */
      propertyListIds?: number[];
      /**
       * @description Seat/account ID for this request
       * @example seat_456
       */
      seatId: string;
    };
    Proposal: {
      /**
       * @description Unique identifier for this proposal (you generate this). The tactic ID will be assigned when the proposal is accepted.
       * @example premium-vcpm-display
       */
      proposalId: string;
      /**
       * @description How you would execute this proposal
       * @example Target premium inventory at $2.50 vCPM with 85% viewability
       */
      execution: string;
      /**
       * @description Maximum budget you can effectively manage
       * @example 50000
       */
      budgetCapacity: number;
      pricing: components["schemas"]["TacticPricing"];
      /**
       * @description Identifier for this tactic type
       * @example premium-vcpm
       */
      sku?: string;
      /** @description Custom fields needed to execute this proposal */
      customFieldsRequired?: components["schemas"]["CustomField"][];
      /**
       * @description Generic blob to store additional information about the proposal that will be passed back when accepted
       * @example {
       *   "property_list": [
       *     "prop1",
       *     "prop2"
       *   ],
       *   "custom_data": "value"
       * }
       */
      additional_info?: Record<string, never>;
    };
    GetProposalsResponse: {
      /** @description List of proposals you can provide (empty array if none) */
      proposals?: components["schemas"]["Proposal"][];
    };
    CampaignContext: {
      /**
       * @description Budget allocated
       * @example 50000
       */
      budget?: number;
      /**
       * @description Currency for budget (ISO 4217 code)
       * @default USD
       * @example USD
       */
      budgetCurrency?: string;
      /**
       * Format: date-time
       * @description Campaign start date in UTC (ISO 8601 format)
       * @example 2025-01-01T00:00:00Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @description Campaign end date in UTC (ISO 8601 format)
       * @example 2025-01-31T23:59:59Z
       */
      endDate?: string;
      /**
       * @description Advertising channel (from ADCP specification)
       * @example display
       * @enum {string}
       */
      channel?: "display" | "video" | "native" | "audio" | "connected_tv";
      /**
       * @description Target countries
       * @example [
       *   "US"
       * ]
       */
      countries?: string[];
      /** @description Creative assets to use (uses Creative from main schema) */
      creatives?: components["schemas"]["Creative"][];
      /** @description Brand safety and suitability requirements (uses BrandStandard from main schema) */
      brandStandards?: components["schemas"]["BrandStandard"][];
    };
    AcceptProposalRequest: {
      /**
       * @description ID of the tactic from the strategy table (assigned when user accepts your proposal)
       * @example 12345
       */
      tacticId: string;
      /**
       * @description ID of the proposal that was accepted (matches proposalId from GetProposalsResponse)
       * @example premium-vcpm-display
       */
      proposalId?: string;
      campaignContext: components["schemas"]["CampaignContext"];
      /**
       * @description Brand agent (advertiser) for this campaign
       * @example ba_123
       */
      brandAgentId: string;
      /**
       * @description Seat/account ID
       * @example seat_456
       */
      seatId: string;
      /**
       * @description Custom fields provided by advertiser
       * @example {
       *   "targetVCPM": 2.5
       * }
       */
      customFields?: Record<string, never>;
      /**
       * @description The additional_info blob that was returned in the proposal response
       * @example {
       *   "property_list": [
       *     "prop1",
       *     "prop2"
       *   ],
       *   "custom_data": "value"
       * }
       */
      additional_info?: Record<string, never>;
    };
    AcceptProposalResponse: {
      /**
       * @description true to accept assignment, false to decline
       * @example true
       */
      acknowledged: boolean;
      /**
       * @description Optional reason if declining
       * @example Insufficient budget for effective optimization
       */
      reason?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get proposals from your agent
   * @description Scope3 calls this endpoint when setting up a campaign to ask for proposals
   * from your agent on how you would approach execution.
   *
   * Analyze the campaign and respond with proposals, budget capacity,
   * and your pricing model.
   */
  get_proposed_tactics: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetProposalsRequest"];
      };
    };
    responses: {
      /** @description Proposals from your agent */
      200: {
        content: {
          "application/json": components["schemas"]["GetProposalsResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        content: never;
      };
      /** @description Internal error */
      500: {
        content: never;
      };
    };
  };
  /**
   * Accept or decline proposal assignment
   * @description Scope3 calls this when your proposal is accepted and you are assigned to manage a tactic.
   * You should acknowledge and begin setup, or decline if you can't fulfill it.
   *
   * The campaign context contains everything you need: budget, schedule,
   * targeting constraints, creatives, and any custom fields.
   */
  accept_proposal: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptProposalRequest"];
      };
    };
    responses: {
      /** @description Acknowledgment of tactic assignment */
      200: {
        content: {
          "application/json": components["schemas"]["AcceptProposalResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        content: never;
      };
    };
  };
}
